import styles from './layout.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
     <nav className={styles.nav}>
      <Link href="/products/woman">여성복</Link>
      <Link href="/products/man">남성복</Link>
      </nav>
      <section className={styles.product}>{children}</section>
    </>
  )
}
