import styles from './layout.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
     <nav className={styles.nav}>
      <a href="">여성복</a>
      <a href="">남성복</a>
      </nav>
      <section className={styles.product}>{children}</section>
    </>
  )
}
